config/routes.rb
Rails.application.routes.draw do
  resources :restaurants, only: [:index, :create, :show]

  post '/create', to: 'restaurants#create'

  # Make every request to go to restaurants#index
  get '(*path)', to: 'restaurants#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
# == Schema Information
#
# Table name: restaurants
#
#  id         :integer          not null, primary key
#  name       :string
#  cuisine    :string
#  rating     :integer
#  tenbis     :boolean
#  address    :string
#  max_time   :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  kosher     :boolean          not null
#  lat        :decimal(9, 6)
#  lng        :decimal(9, 6)
#

class Restaurant < ApplicationRecord
  validates :name, :cuisine, :rating, :address, :max_time, presence: true
  validates :rating, numericality: true
  validates :rating, inclusion: 1..3
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/concerns/default_serializer_concern.rb
module DefaultSerializerConcern
  extend ActiveSupport::Concern

  included do
    def self.default_serializer
      @_default_serializer
    end

    def self.default_serializer=(klass)
      @_default_serializer = klass
    end
  end

  def default_serializer
    self.class.default_serializer
  end

  # def render(options)
  #   if options[:json].respond_to?(:each)
  #     options = {each_serializer: default_serializer}.merge(options)
  #   else
  #     options = {serializer: default_serializer}.merge(options)
  #   end
  #   super(options)
  # end
end

app/controllers/restaurant_serializer.rb
class RestaurantSerializer < ActiveModel::Serializer
  attributes :name, :cuisine, :rating, :tenbis, :address, :max_time, :kosher, :lat, :lng
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  include DefaultSerializerConcern
  skip_before_action :verify_authenticity_token, only: [:create]

  # self.default_serializer = RestaurantSerializer


  layout "restaurants"
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  # GET /Restaurants
  # GET /Restaurants.json
  def index
    @restaurants_props = { restaurants: Restaurant.all }
  end

  # GET /Restaurants/1
  # GET /Restaurants/1.json
  def show
  end

  # GET /Restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /Restaurants/1/edit
  def edit
  end

  # POST /Restaurants
  # POST /Restaurants.json
  def create
    @restaurant = Restaurant.new(restaurant_params)

    respond_to do |format|
      if @restaurant.save
        # format.html { redirect_to @restaurant, notice: 'Restaurant was successfully created.' }
        format.json { render status: :created, json: @restaurant, serializer: RestaurantSerializer }
      else
        format.html { render :new }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /Restaurants/1
  # PATCH/PUT /Restaurants/1.json
  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /Restaurants/1
  # DELETE /Restaurants/1.json
  def destroy
    @restaurant.destroy
    respond_to do |format|
      format.html { redirect_to restaurants_url, notice: 'Restaurant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def restaurant_params
      params.require(:restaurant).permit(:name, :cuisine, :rating, :tenbis, :address, :max_time, :kosher, :lat, :lng)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WeEat :: fgdfd</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <!-- Latest compiled and minified CSS -->

  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body class='<%= controller.controller_name %>'>
<%= yield %>
</body>
</html>

app/views/layouts/restaurants.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WeEat</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'webpack-bundle' %>
</head>

<body>
<%= yield %>
</body>
</html>

app/views/restaurants/_form.html.erb
<%= form_with(model: restaurant, local: true) do |form| %>
  <% if restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

      <ul>
      <% restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :restaurant_name %>
  </div>

  <div class="field">
    <%= form.label :cuisine %>
    <%= form.text_field :cuisine, id: :restaurant_cuisine %>
  </div>

  <div class="field">
    <%= form.label :rating %>
    <%= form.number_field :rating, id: :restaurant_rating %>
  </div>

  <div class="field">
    <%= form.label :tenbis %>
    <%= form.check_box :tenbis, id: :restaurant_tenbis %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address, id: :restaurant_address %>
  </div>

  <div class="field">
    <%= form.label :max_time %>
    <%= form.number_field :max_time, id: :restaurant_max_time %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Editing Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Show', @restaurant %> |
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<%= react_component('RestaurantsApp', props: @restaurants_props, prerender: false) %>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @restaurant.name %>
</p>

<p>
  <strong>Cuisine:</strong>
  <%= @restaurant.cuisine %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @restaurant.rating %>
</p>

<p>
  <strong>Tenbis:</strong>
  <%= @restaurant.tenbis %>
</p>

<p>
  <strong>Address:</strong>
  <%= @restaurant.address %>
</p>

<p>
  <strong>Max time:</strong>
  <%= @restaurant.max_time %>
</p>

<%= link_to 'Edit', edit_restaurant_path(@restaurant) %> |
<%= link_to 'Back', restaurants_path %>